site_name: Guide Book
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  feature:
    - navigation.path
    - navigation.indexes
    - navigation.tracking
nav:
  - Introduction: introduction.md
  #- Folder Structure:
  
