site_name: Guide Book
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  feature:
    - navigation.path
    - navigation.indexes
    - navigation.tracking

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introduction: introduction.md
  - Folder Structure: folder-structure.md
  - Build system: build-system.md
  - Git version control: git.md
  - Dependencies management: dependency-manage.md
  - Configurations: configurations.md
  - Testing: test.md
  - Docker: docker.md
